;;;; zhelpers.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'zhelpers
  'zhelpers
  (scheme#list)
  '((s_send . zhelpers#s_send))
  (scheme#list)
  (scheme#list))

;; END OF FILE
