;;;; zmq.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'zmq
  'zmq
  (scheme#list)
  '((ZMQ_REQ . zmq#ZMQ_REQ)
    (ZMQ_REP . zmq#ZMQ_REP)
    (zmq_connect . zmq#zmq_connect)
    (zmq_ctx_destroy . zmq#zmq_ctx_destroy)
    (zmq_close . zmq#zmq_close)
    (zmq_send . zmq#zmq_send)
    (zmq_recv . zmq#zmq_recv)
    (zmq_bind . zmq#zmq_bind)
    (zmq_socket . zmq#zmq_socket)
    (zmq_errno . zmq#zmq_errno)
    (zmq_ctx_get . zmq#zmq_ctx_get)
    (zmq_ctx_new . zmq#zmq_ctx_new))
  (scheme#list)
  (scheme#list))

;; END OF FILE
