;;;; zsugar.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(scheme#eval
  '(import-syntax
     scheme
     chicken.base
     (except chicken.foreign location)
     chicken.syntax
     chicken.process-context
     chicken.memory
     srfi-1
     srfi-13
     zmq
     zhelpers))
(##sys#register-compiled-module
  'zsugar
  'zsugar
  (scheme#list)
  '()
  (scheme#list
    (scheme#cons
      'forever
      (syntax-rules
        ()
        ((forever (break) body ...)
         (call/cc (lambda (break) (let loop () body ... (loop)))))
        ((forever body ...) (forever (_) body ...))))
    (scheme#cons
      '✓₀
      (syntax-rules () ((✓₀ sexp) (assert (equal? 0 sexp)))))
    (scheme#cons
      'zmq-socket
      (syntax-rules
        (ZMQ_SUB)
        ((zmq-socket ctx () body ...) (begin body ...))
        ((zmq-socket ctx ((socket (ZMQ_SUB sub)) other ...) body ...)
         (zmq-socket
           ctx
           ((socket ZMQ_SUB) other ...)
           (begin
             (✓₀
               (zmq_setsockopt
                 socket
                 ZMQ_SUBSCRIBE
                 (location sub)
                 (string-length sub)))
             body
             ...)))
        ((zmq-socket ctx ((socket type) other ...) body ...)
         (let ((socket (zmq_socket ctx type)))
           (zmq-socket cts (other ...) body ... (zmq_close socket))))))
    (scheme#cons
      'zmq-context
      (syntax-rules
        ()
        ((zmq-context (ctx ...) body ...)
         (let ((ctx (zmq_ctx_new)) ...) body ... (zmq_ctx_destroy ctx) ...)))))
  (scheme#list))

;; END OF FILE
